//
//  f6-4P109.c
//  Graph
//
//  Created by 冨澤眞樹 on 2018/12/20.
//  Copyright © 2018年 tomisawa. All rights reserved.
//

#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>

#define NV 7  // number of vertices
#define NE 22 // number of edges

#define PRINTG(GRAPH)                                            \
  do {                                                           \
    printf(#GRAPH "\n");                                         \
    PringGraph((float *)GRAPH, sizeof(GRAPH) / sizeof(GRAPH[0]), \
        sizeof(GRAPH[0]) / sizeof(GRAPH[0][0]));                 \
  } while (0);

typedef struct ADList {
  int v;
  float w;
  struct ADList *next;
} ADList;

ADList *vertex[NV];
ADList edge[NE];

float F64[][NV]= {
    //  1  2  3  4  5  6
    {0, 0, 0, 0, 0, 0, 0}, //
    {0, 0, 5, 0, 1, 3, 0}, // 1
    {0, 5, 0, 6, 7, 2, 0}, // 2
    {0, 0, 6, 0, 5, 0, 3}, // 3
    {0, 1, 7, 5, 0, 4, 2}, // 4
    {0, 3, 2, 0, 4, 0, 1}, // 5
    {0, 0, 0, 3, 2, 1, 0}  // 6

};

// The body of MakeList() was generated by
// a conversion program from adjacency matrix to adjacency list.
void MakeList() {
  vertex[1]= &edge[0];
  edge[0].v= 2;
  edge[0].w= 5.0;
  edge[0].next= &edge[1];
  edge[1].v= 4;
  edge[1].w= 1.0;
  edge[1].next= &edge[2];
  edge[2].v= 5;
  edge[2].w= 3.0;
  edge[2].next= 0;
  vertex[2]= &edge[3];
  edge[3].v= 1;
  edge[3].w= 5.0;
  edge[3].next= &edge[4];
  edge[4].v= 3;
  edge[4].w= 6.0;
  edge[4].next= &edge[5];
  edge[5].v= 4;
  edge[5].w= 7.0;
  edge[5].next= &edge[6];
  edge[6].v= 5;
  edge[6].w= 2.0;
  edge[6].next= 0;
  vertex[3]= &edge[7];
  edge[7].v= 2;
  edge[7].w= 6.0;
  edge[7].next= &edge[8];
  edge[8].v= 4;
  edge[8].w= 5.0;
  edge[8].next= &edge[9];
  edge[9].v= 6;
  edge[9].w= 3.0;
  edge[9].next= 0;
  vertex[4]= &edge[10];
  edge[10].v= 1;
  edge[10].w= 1.0;
  edge[10].next= &edge[11];
  edge[11].v= 2;
  edge[11].w= 7.0;
  edge[11].next= &edge[12];
  edge[12].v= 3;
  edge[12].w= 5.0;
  edge[12].next= &edge[13];
  edge[13].v= 5;
  edge[13].w= 4.0;
  edge[13].next= &edge[14];
  edge[14].v= 6;
  edge[14].w= 2.0;
  edge[14].next= 0;
  vertex[5]= &edge[15];
  edge[15].v= 1;
  edge[15].w= 3.0;
  edge[15].next= &edge[16];
  edge[16].v= 2;
  edge[16].w= 2.0;
  edge[16].next= &edge[17];
  edge[17].v= 4;
  edge[17].w= 4.0;
  edge[17].next= &edge[18];
  edge[18].v= 6;
  edge[18].w= 1.0;
  edge[18].next= 0;
  vertex[6]= &edge[19];
  edge[19].v= 3;
  edge[19].w= 3.0;
  edge[19].next= &edge[20];
  edge[20].v= 4;
  edge[20].w= 2.0;
  edge[20].next= &edge[21];
  edge[21].v= 5;
  edge[21].w= 1.0;
  edge[21].next= 0;
}

void PringGraph(float g[], int row, int column) {
  for (int i= 1; i < row; i++) {
    printf("v[%d] ", i);
    for (int j= 1; j < column; j++)
      if (!g[i * column + j]) printf("(%d, %.1f)", j, g[i * column + j]);
    printf("\n");
  }
  printf("---\n");
}

void PrintList() {
  ADList *p;
  for (int v= 1; v < NV; v++) {
    if (!vertex[v]) {
      printf("v[%d]=isolated vertex\n", v);
      continue;
    }
    printf("v[%d] ", v);
    p= vertex[v];
    do {
      printf("(%d, %0.1f)", p->v, p->w);
      p= p->next;
    } while (p);
    printf("\n");
  }
}

int main(int argc, const char *argv[]) {
  PRINTG(F64);
  MakeList();
  PrintList();
}
